In [4]:
import torch

* 张量的索引与切片

In [10]:
# arange 类似range生成从0到n-1的张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
# 即是调用最后一行
X[-1]

tensor([ 8,  9, 10, 11])